CREATE TABLE PROVEEDOR(
  ID INT(4)  NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  PAIS VARCHAR(40) NOT NULL,
  CONSTRAINT pkPROVEEDOR PRIMARY KEY (ID)
);
CREATE TABLE ARTICULO(
  ID INT(4) NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  DESCRIPCION VARCHAR(50),
  ID_PROVEEDOR INT(4) NOT NULL,
  CONSTRAINT pkARTICULO PRIMARY KEY (ID),
  CONSTRAINT fkPROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID)
);


